# Generated by Django 3.1.2 on 2020-10-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
