# Generated by Django 3.1.2 on 2020-10-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaHealthApp', '0003_usersinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('reason', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'UsersAppointments',
            },
        ),
    ]
